export const HOME_URL = '/'
export const IPD_URL = '/'
export const PRESIDENCIA_URL = '/'
export const ASESORIA_JURIDICA_URL = '/'
export const CAPITAL_HUMANO_URL = '/'
export const NEGOCIOS_URL = '/'
export const ECONOMIA_URL = '/'
export const LOGISTICA_URL = '/'
